#!/bin/sh
#
# @name Gazebo x500_e2e_widecam (DATABOSS Phase 20A)
#
# @type Quadrotor
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500_e2e_widecam}

. ${R}etc/init.d-posix/airframes/4001_gz_x500

param set-default EKF2_OF_DELAY 111
